
from enum import IntEnum
from typing import NamedTuple, Optional
from BaseClasses import Item, ItemClassification

class EBF5Item(Item):
    game: str = "Epic Battle Fantasy 5"
 
class EBF5ItemCategory(IntEnum): 
    KEY_ITEM        = 1
    KEY             = 2  # as in keys for blocks
    QUEST           = 3
    SHOP            = 4
    SEASONAL        = 5
    EQUIPMENT       = 6
    SWORD           = 7
    STAFF           = 8
    GUN             = 9
    BOW             = 10
    TOY             = 11
    MALE_HATS       = 12
    MALE_ARMOR      = 13
    FEMALE_HATS     = 14
    FEMALE_ARMOR    = 15
    FLAIR           = 16
    CONSUMABLE      = 17 # food ect.
    BOOSTER         = 18
    CARD            = 19
    SKILL           = 20
    LIMIT_BREAK     = 21

class ItemData(NamedTuple):
    id: Optional[int]
    name: str
    category: list[EBF5ItemCategory]
    classification: ItemClassification
    is_unique: bool = True
    max_amount: int = 1

items = [
    # Key Items
    ItemData(5000, "Magnetic Boots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5001, "Leafy Boots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5002, "Spiked Boots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5003, "Thermal Boots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5004, "Winged Boots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5005, "The Shovel", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5006, "The Hammer", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5007, "The Axe", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5008, "The Stepladder", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5009, "The Raft", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5010, "The Candle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5011, "The Big Hammer", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5012, "Stone Head", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 6),
    ItemData(5013, "Topaz Key", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.KEY], ItemClassification.progression, False, 4),
    ItemData(5014, "Coral Key", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.KEY], ItemClassification.progression, False, 6),
    ItemData(5015, "Copper Key", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.KEY], ItemClassification.progression, False, 4),
    ItemData(5016, "Gold Key", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.KEY], ItemClassification.progression, False, 6),
    ItemData(5017, "Diamond Key", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.KEY], ItemClassification.progression, False, 4),
    ItemData(5018, "Wooden Key", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.KEY], ItemClassification.progression, False, 5),
    ItemData(5019, "Earth Orb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5020, "Wind Orb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5021, "Fire Orb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5022, "Water Orb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5023, "Emerald of Life", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5024, "Sapphire of Dreams", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    ItemData(5025, "Ruby of Death", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, True, 1),
    # Progression
    ItemData(None, "Post-Jotun", [], ItemClassification.progression, True, 1),              #5026
    ItemData(None, "Post-Neon Valkyrie", [], ItemClassification.progression, True, 1),      #5027
    ItemData(None, "Post-Laurelin", [], ItemClassification.progression, True, 1),           #5028
    ItemData(None, "Post-Poseidon", [], ItemClassification.progression, True, 1),           #5029
    ItemData(None, "Defeated Sol & Skadi", [], ItemClassification.progression, True, 1),    #5030
    ItemData(None, "Defeated Neon Valhalla", [], ItemClassification.progression, True, 1),  #5031
    ItemData(None, "Defeated Telperion", [], ItemClassification.progression, True, 1),      #5032
    ItemData(None, "Defeated Vulcan", [], ItemClassification.progression, True, 1),         #5033
    ItemData(None, "Defeated Crystal Hydra", [], ItemClassification.progression, True, 1),  #5034
    # Equipment
    ItemData(5035, "Heaven's Gate", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5036, "Berzerker", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5037, "Inferno", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5038, "Ice Needle", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5039, "Lightning Shard", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5040, "Sapphire Saint", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5041, "Black Fang", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5042, "The Chopper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5043, "Giant Slayer", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5044, "Hyper Drill", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5045, "Emerald Smasher", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5046, "Devil's Fork", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5047, "Club of Withering", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5048, "Crimson Razorback", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5049, "Dragon's Feather", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5050, "Golden Axe", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5051, "Dark Stalker", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5052, "Fusion Blade", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5053, "Soul Eater", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful, True, 1),
    ItemData(5054, "Love Blade", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5055, "Sol Spear", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5056, "Arctic Trident", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5057, "Wrath of Zeus", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5058, "Druid Staff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5059, "Nimbus Rod", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5060, "Dragon Wings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5061, "Gigavolt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5062, "Alchemy Set", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5063, "Kaladanda", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5064, "Wrecking Rod", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5065, "Elder's Wisdom", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5066, "Obsidian Staff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5067, "Celtic Cross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5068, "The Knife", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5069, "Paper Fan", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5070, "Oak Staff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5071, "Beholding Eye", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5072, "Soul Crusher", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5073, "Shooting Star", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful, True, 1),
    ItemData(5074, "Slime Staff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF, EBF5ItemCategory.SHOP, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5075, "Nitro Bomber XL", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5076, "Hellfire Shotgun", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5077, "Thunder Core", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5078, "Deep Blue", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5079, "Chainsaw Gun", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5080, "Vortex Cannon", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5081, "Sub Zero", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5082, "Biohazard Blaster", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5083, "Crystal Wing", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5084, "Heavy Claw", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5085, "Soul Pistol", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5086, "Super Snipe ZX", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5087, "Coconut Shooter", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5088, "Flame Titan", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5089, "Heartstopper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5090, "Gungnir", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5091, "Spine Snapper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5092, "Desert Scorpion", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5093, "Accelerator", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5094, "Green Goliath", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful, True, 1),
    ItemData(5095, "Cold Steel", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5096, "Thor's Hammer", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5097, "Aquamarine", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5098, "Gaia's Gift", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5099, "Crimson Dragon", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5100, "Iron Tusk", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5101, "Fenrir's Jaw", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5102, "The Deceased", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5103, "Juggernaut", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5104, "Emerald Cyclone", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5105, "Eagle Eye", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5106, "The Stinger", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5107, "Chieftain's Horns", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5108, "Regal Turtle", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5109, "Alchemist's Bow", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5110, "Black Widow", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5111, "Angel Wing", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5112, "Sharanga", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5113, "Earth's Whisper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful, True, 1),
    ItemData(5114, "Heaven's Voice", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5115, "Bandit Blade", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5116, "Neon Lightbulb", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5117, "Honjo Masamune", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5118, "Riot Shield", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5119, "Leaf Shield", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5120, "Star Hammer", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5121, "Dog Sausage", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5122, "Icecream Sandwich", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5123, "Godly Book", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5124, "Human Skull", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5125, "Blood Bank", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5126, "Viking Buckler", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5127, "Turtle Shell", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5128, "Elven Shield", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5129, "Pixel Popper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5130, "Book of Spells", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5131, "Power Paw", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5132, "Devil's Sunrise", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5133, "King's Guard", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5134, "Buster Sword", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful, True, 1),
    ItemData(5135, "Horned Helmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5136, "Spartan Helmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5137, "Genji Helmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5138, "Basket Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5139, "Dragon Helm", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5140, "Army Helmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5141, "Space Helmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5142, "Scottish Cap", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5143, "Spelunking Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5144, "Wizard Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5145, "Headband", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5146, "Necromancer's Helmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5147, "Cardboard Box", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5148, "Gas Mask", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5149, "Death Mask", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5150, "Puppy Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5151, "Pumpkin Head", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5152, "Santa Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5153, "Captain's Coat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5154, "Viking Fur", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5155, "Spartan Cuirass", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5156, "Genji Armor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5157, "Ninja Gear", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5158, "Dragon Armor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5159, "Camo Jacket", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5160, "Space Ace", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5161, "Scottish Kilt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5162, "Explorer's Jacket", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5163, "Wizard Robe", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5164, "Turtle Gi", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5165, "Flame Suit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5166, "Hipster Shirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5167, "Shell Armor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5168, "Priest's Tunic", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5169, "Coat of Teeth", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5170, "Santa Outfit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5171, "Nurse Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5172, "Fur Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5173, "Pope Hat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5174, "Leafy Hairclip", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5175, "Curly Horns", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5176, "Cat Ears", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5177, "Flower Bobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5178, "Dark Bobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5179, "Slime Bunny", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5180, "Ninja Chopsticks", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5181, "Robot Ears", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5182, "Drill Bits", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5183, "Bunny Ears", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5184, "Ice Shards", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5185, "Royal Crown", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5186, "Rubber Duck", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5187, "Blue Elephant", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful, True, 1),
    ItemData(5188, "Spider Bobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5189, "Holly Hairpin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5190, "Nurse Uniform", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5191, "Fur Dress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5192, "Pope Dress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5193, "Cactus Dress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5194, "Cow Costume", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5195, "Maid Outfit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5196, "Summer Kimono", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5197, "Dark Gown", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5198, "Magical Skirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5199, "Ninja Skirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5200, "Mecha Suit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5201, "Obsidian Armor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5202, "School Uniform", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5203, "Bubble Dress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5204, "Camo Skirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5205, "Sami Dress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5206, "Casual Skirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful, True, 1),
    ItemData(5207, "Spider Gown", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5208, "Santa Skirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5209, "Flame Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5210, "Lightning Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5211, "Frost Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5212, "Pearl Necklace", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5213, "Surgical Mask", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5214, "Angel Pin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5215, "Bandage", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5216, "Iron Cross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5217, "Silver Cross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5218, "Golden Pendant", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5219, "Nano Machines", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5220, "Battle Paint", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5221, "Lucky Clover", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5222, "Hoop Earrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5223, "The Tr*force", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5224, "Green Cross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5225, "Fairy", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5226, "Pocket Watch", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5227, "Meow Meow Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5228, "Captain Viridian", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5229, "Agnry Faic", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5230, "Target Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5231, "Tentacle", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5232, "Peace Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5233, "Crossbone Pin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5234, "Chrome Earrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5235, "Amethyst Earrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5236, "Emerald Earrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5237, "Fat Fly", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5238, "Bitey Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5239, "Baby Penguin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5240, "Pet Rock", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5241, "Tetromino", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5242, "Pixel Glasses", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5243, "Fake Mustache", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5244, "Big Eyebrows", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5245, "RAM Chip", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5246, "Juicy Beast", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5247, "Small Cloud", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5248, "Dinosaur Egg", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5249, "Lucky Fish", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5250, "Coin Charm", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5251, "Mini Drone", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5252, "Heart Pendant", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful, True, 1),
    ItemData(5253, "The One R*ng", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5254, "Companion C*be", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5255, "Dog Tags", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5256, "Narutomaki", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5257, "Cat Tail", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5258, "Tooth", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5259, "Balance Badge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5260, "Sword Medal", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5261, "Shield Medal", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5262, "Gold Star", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    ItemData(5263, "Platinum Star", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful, True, 1),
    # Cards
    ItemData(5264, "Card 01 (Baby Bush)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5265, "Card 02 (Big Bush)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5266, "Card 03 (Bazooka Bush)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5267, "Card 04 (Creepy Idol)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5268, "Card 05 (Undead Boulder)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5269, "Card 06 (Snarky Radish)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5270, "Card 07 (Snarky Tree)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5271, "Card 08 (Eyeball Plant)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5272, "Card 09 (Beholding Bat)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5273, "Card 10 (Beholding Beast)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5274, "Card 11 (Potted Gloop)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5275, "Card 12 (Crystal Gloop)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5276, "Card 13 (Sandstone Gloop)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5277, "Card 14 (Famine Face)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5278, "Card 15 (Frosty Face)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5279, "Card 16 (Fire Face)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5280, "Card 17 (Cursed Medallion)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5281, "Card 18 (Cursed Chest)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5282, "Card 19 (Spy Satellite)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5283, "Card 20 (Flybot Drone)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5284, "Card 21 (Lava Slime)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5285, "Card 22 (Magma Slime)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5286, "Card 23 (Volcano Slime)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5287, "Card 24 (Touchy Octopus)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5288, "Card 25 (Angry Bee)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5289, "Card 26 (Fighter Bee)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5290, "Card 27 (Mountain Goat)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5291, "Card 28 (Chibi Robot)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5292, "Card 29 (Dai Robot)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5293, "Card 30 (Normal Turtle)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5294, "Card 31 (Derpy Turtle)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5295, "Card 32 (Titanic Turtle)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5296, "Card 33 (Sea Jelly)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5297, "Card 34 (Electron Child)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5298, "Card 35 (Electron Cloud)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5299, "Card 36 (Electron Knight)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5300, "Card 37 (Sacred Guardian)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5301, "Card 38 (Evil Fungus)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5302, "Card 39 (Ice Mite)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5303, "Card 40 (Ice Roach)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5304, "Card 41 (Pupper)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5305, "Card 42 (Doggo)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5306, "Card 43 (Specter)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5307, "Card 44 (Hollow Soldier)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5308, "Card 45 (Fire Elemental)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5309, "Card 46 (Donut Snake)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5310, "Card 47 (Toaster)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5311, "Card 48 (Baby Bacon)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5312, "Card 49 (Bacon Roll)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    ItemData(5313, "Card 50 (Adult Bacon)", [EBF5ItemCategory.CARD], ItemClassification.useful, True, 1),
    # Skills
    ItemData(5314, "Ivy", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5315, "Acid", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5316, "Gale", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5317, "Shock", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5318, "Sand", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5319, "Bullet Bob", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5320, "Purging Flame", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5321, "Giga Drill", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5322, "Electron Gun", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5323, "Bubble Ring", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5324, "Gaia Seed", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5325, "Bubble", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5326, "Air", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5327, "Energy", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5328, "Sawblade", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5329, "Snow Bunnies", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5330, "Fire Spin", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5331, "Fairy Bombs", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5332, "Demon Swords", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5333, "Geometry", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5334, "Encore", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5335, "Power Metal", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5336, "Screamer", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5337, "The Reaper", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5338, "Lock On", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5339, "Heavenly Shield", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5340, "Reflex", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5341, "Enfeeble", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5342, "Sharpen", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5343, "Bind", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5344, "Flare", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5345, "Revive", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5346, "Purify", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5347, "Phyrnna's Blessing", [EBF5ItemCategory.SKILL], ItemClassification.useful, True, 1),
    ItemData(5348, "Firecrackers", [EBF5ItemCategory.SKILL, EBF5ItemCategory.SEASONAL], ItemClassification.useful, True, 1),
    ItemData(5349, "Annihalate", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5350, "Supernova", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5351, "Absolute Zero", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5352, "Tsunami", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5353, "Black Hole", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5354, "Seven Swords", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5355, "Death Metal", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5356, "Hidden Power", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    ItemData(5357, "Art Attack", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful, True, 1),
    # Consumables / Other
    ItemData(5358, "Espresso", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 4),
    ItemData(5359, "Chili Pepper", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 4),
    ItemData(5360, "Pizza", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 4),
    ItemData(5361, "Physical Steroids Pack", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 5),
    ItemData(5362, "Magical Steroids Pack", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 5),
    ItemData(5363, "Accuracy/Evasion Steroids Pack", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 5),
    ItemData(5364, "Health Steroids Pack", [EBF5ItemCategory.CONSUMABLE], ItemClassification.filler, False, 5)
]
